var jcm_poros_capPos = 'Bottom';
var jcm_poros_headerColorOption = 'Theme Default';
var jcm_poros_textColorOption = 'Theme Default';
var jcm_poros_fontFamilyOption = 'Theme Default';
var jcm_poros_headerColor = '#c16';
var jcm_poros_textColor = '#fff';
var jcm_poros_fontFamilyVal = 'Arial';
var jcm_poros_caption_headerOption = 'On';
var jcm_poros_caption_textOption = 'On';
